/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS
 */
public class formInicio extends javax.swing.JFrame {

    /**
     * Creates new form frminicio
     */
    public formInicio() {
        initComponents();
        this.setExtendedState(formInicio.MAXIMIZED_BOTH);
        this.setTitle("Sistema de Reserva de Habitaciones y Gestión de ventas - Hostal Olympo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        lblacceso = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblapaterno = new javax.swing.JLabel();
        lblamaterno = new javax.swing.JLabel();
        lblidpersona = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuServicios = new javax.swing.JMenu();
        Habitaciones = new javax.swing.JMenuItem();
        Productos = new javax.swing.JMenuItem();
        menuReservas = new javax.swing.JMenu();
        ReservasConsumos = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenuItem();
        menuAccesos = new javax.swing.JMenu();
        Usuarios = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        AcercaDe = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(153, 153, 153));

        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/usuario.png"))); // NOI18N
        Usuario.setMaximumSize(new java.awt.Dimension(512, 512));
        Usuario.setMinimumSize(new java.awt.Dimension(512, 512));
        Usuario.setPreferredSize(new java.awt.Dimension(512, 512));

        lblacceso.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblacceso.setText("jLabel7");

        lblnombre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblnombre.setText("jLabel2");

        lblapaterno.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblapaterno.setText("jLabel3");

        lblamaterno.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblamaterno.setText("jLabel4");

        lblidpersona.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblidpersona.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblacceso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblidpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lblapaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblamaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblacceso)
                            .addComponent(lblidpersona))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombre)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblapaterno)
                                .addComponent(lblamaterno)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/ServicioHabitacion.png"))); // NOI18N
        menuServicios.setMnemonic('e');
        menuServicios.setText("Servicios");

        Habitaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        Habitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Habitaciones2.png"))); // NOI18N
        Habitaciones.setMnemonic('t');
        Habitaciones.setText("Habitaciones");
        Habitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabitacionesActionPerformed(evt);
            }
        });
        menuServicios.add(Habitaciones);

        Productos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Productos2.png"))); // NOI18N
        Productos.setMnemonic('y');
        Productos.setText("Productos");
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });
        menuServicios.add(Productos);

        menuBar.add(menuServicios);

        menuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Reservaciones.png"))); // NOI18N
        menuReservas.setMnemonic('h');
        menuReservas.setText("Reservas");

        ReservasConsumos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        ReservasConsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/ReservasConsumos.png"))); // NOI18N
        ReservasConsumos.setMnemonic('c');
        ReservasConsumos.setText("Reservas y Consumos");
        ReservasConsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasConsumosActionPerformed(evt);
            }
        });
        menuReservas.add(ReservasConsumos);

        Clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Clientes2.png"))); // NOI18N
        Clientes.setMnemonic('a');
        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        menuReservas.add(Clientes);

        menuBar.add(menuReservas);

        menuAccesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Configuraciones.png"))); // NOI18N
        menuAccesos.setText("Accesos");

        Usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/trabajadores.png"))); // NOI18N
        Usuarios.setText("Usuarios");
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        menuAccesos.add(Usuarios);

        menuBar.add(menuAccesos);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Help.png"))); // NOI18N
        menuAyuda.setText("Centro de Ayuda");

        AcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        AcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/acerca de.png"))); // NOI18N
        AcercaDe.setText("Acerca de...");
        AcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(AcercaDe);

        Ayuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Ayuda2.png"))); // NOI18N
        Ayuda.setText("Ayuda");
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });
        menuAyuda.add(Ayuda);

        menuBar.add(menuAyuda);

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Exit.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuBar.add(menuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Para ayuda y asesoramiento de uso del software, contacte al correo: "
                + "torrespastor4@hotmail.com");
    }//GEN-LAST:event_AyudaActionPerformed

    private void HabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabitacionesActionPerformed
        // TODO add your handling code here:
        FrmHabitacion form =new FrmHabitacion();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_HabitacionesActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
        // TODO add your handling code here:
        FrmProducto form =new FrmProducto();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_ProductosActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
        FrmCliente form =new FrmCliente();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_ClientesActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        // TODO add your handling code here:
        FrmTrabajador form =new FrmTrabajador();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_UsuariosActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuSalirMouseClicked

    private void ReservasConsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasConsumosActionPerformed
        // TODO add your handling code here:
        FrmReserva form = new FrmReserva();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        FrmReserva.txtidtrabajador.setText(lblidpersona.getText());
        FrmReserva.txttrabajador.setText(lblnombre.getText() + " " + lblapaterno.getText());
        FrmReserva.id_usuario=Integer.parseInt(lblidpersona.getText());
    }//GEN-LAST:event_ReservasConsumosActionPerformed

    private void AcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaDeActionPerformed
       JOptionPane.showMessageDialog(rootPane, "Sistema de Reserva de Habitaciones y Gestión de ventas "
                + "realizado por Jorge Anthony Torres Pastor");
    }//GEN-LAST:event_AcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AcercaDe;
    private javax.swing.JMenuItem Ayuda;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenuItem Habitaciones;
    private javax.swing.JMenuItem Productos;
    private javax.swing.JMenuItem ReservasConsumos;
    private javax.swing.JLabel Usuario;
    private javax.swing.JMenuItem Usuarios;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblacceso;
    public static javax.swing.JLabel lblamaterno;
    public static javax.swing.JLabel lblapaterno;
    public static javax.swing.JLabel lblidpersona;
    public static javax.swing.JLabel lblnombre;
    public static javax.swing.JMenu menuAccesos;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuReservas;
    private javax.swing.JMenu menuSalir;
    public static javax.swing.JMenu menuServicios;
    // End of variables declaration//GEN-END:variables

}
